# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='core.proto',
  package='nano.api',
  syntax='proto3',
  serialized_pb=_b('\n\ncore.proto\x12\x08nano.api\x1a\x1egoogle/protobuf/wrappers.proto\".\n\x07request\x12#\n\x04type\x18\x01 \x01(\x0e\x32\x15.nano.api.RequestType\"r\n\x08response\x12#\n\x04type\x18\x01 \x01(\x0e\x32\x15.nano.api.RequestType\x12\x12\n\nerror_code\x18\x02 \x01(\x11\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x16\n\x0e\x65rror_category\x18\x04 \x01(\t\"\x16\n\x08req_ping\x12\n\n\x02id\x18\x01 \x01(\r\"\x16\n\x08res_ping\x12\n\n\x02id\x18\x01 \x01(\r*K\n\nAPIVersion\x12\x13\n\x0fVERSION_INVALID\x10\x00\x12\x11\n\rVERSION_MAJOR\x10\x01\x12\x11\n\rVERSION_MINOR\x10\x00\x1a\x02\x10\x01*d\n\x0bRequestType\x12\x0b\n\x07INVALID\x10\x00\x12\x15\n\x11REGISTER_CALLBACK\x10\x01\x12\x08\n\x04PING\x10\x02\x12\x13\n\x0f\x41\x43\x43OUNT_PENDING\x10\x64\x12\x12\n\rADDRESS_VALID\x10\xe8\x07\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])

_APIVERSION = _descriptor.EnumDescriptor(
  name='APIVersion',
  full_name='nano.api.APIVersion',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VERSION_INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERSION_MAJOR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERSION_MINOR', index=2, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=_descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\020\001')),
  serialized_start=268,
  serialized_end=343,
)
_sym_db.RegisterEnumDescriptor(_APIVERSION)

APIVersion = enum_type_wrapper.EnumTypeWrapper(_APIVERSION)
_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='nano.api.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REGISTER_CALLBACK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PING', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCOUNT_PENDING', index=3, number=100,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADDRESS_VALID', index=4, number=1000,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=345,
  serialized_end=445,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTYPE)

RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)
VERSION_INVALID = 0
VERSION_MAJOR = 1
VERSION_MINOR = 0
INVALID = 0
REGISTER_CALLBACK = 1
PING = 2
ACCOUNT_PENDING = 100
ADDRESS_VALID = 1000



_REQUEST = _descriptor.Descriptor(
  name='request',
  full_name='nano.api.request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='nano.api.request.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=102,
)


_RESPONSE = _descriptor.Descriptor(
  name='response',
  full_name='nano.api.response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='nano.api.response.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='nano.api.response.error_code', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='nano.api.response.error_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_category', full_name='nano.api.response.error_category', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=218,
)


_REQ_PING = _descriptor.Descriptor(
  name='req_ping',
  full_name='nano.api.req_ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='nano.api.req_ping.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=242,
)


_RES_PING = _descriptor.Descriptor(
  name='res_ping',
  full_name='nano.api.res_ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='nano.api.res_ping.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=266,
)

_REQUEST.fields_by_name['type'].enum_type = _REQUESTTYPE
_RESPONSE.fields_by_name['type'].enum_type = _REQUESTTYPE
DESCRIPTOR.message_types_by_name['request'] = _REQUEST
DESCRIPTOR.message_types_by_name['response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['req_ping'] = _REQ_PING
DESCRIPTOR.message_types_by_name['res_ping'] = _RES_PING
DESCRIPTOR.enum_types_by_name['APIVersion'] = _APIVERSION
DESCRIPTOR.enum_types_by_name['RequestType'] = _REQUESTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'core_pb2'
  # @@protoc_insertion_point(class_scope:nano.api.request)
  ))
_sym_db.RegisterMessage(request)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'core_pb2'
  # @@protoc_insertion_point(class_scope:nano.api.response)
  ))
_sym_db.RegisterMessage(response)

req_ping = _reflection.GeneratedProtocolMessageType('req_ping', (_message.Message,), dict(
  DESCRIPTOR = _REQ_PING,
  __module__ = 'core_pb2'
  # @@protoc_insertion_point(class_scope:nano.api.req_ping)
  ))
_sym_db.RegisterMessage(req_ping)

res_ping = _reflection.GeneratedProtocolMessageType('res_ping', (_message.Message,), dict(
  DESCRIPTOR = _RES_PING,
  __module__ = 'core_pb2'
  # @@protoc_insertion_point(class_scope:nano.api.res_ping)
  ))
_sym_db.RegisterMessage(res_ping)


_APIVERSION.has_options = True
_APIVERSION._options = _descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
