# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: util.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='util.proto',
  package='nano.api',
  syntax='proto3',
  serialized_pb=_b('\n\nutil.proto\x12\x08nano.api\"$\n\x11req_address_valid\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"2\n\x11res_address_valid\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\tb\x06proto3')
)




_REQ_ADDRESS_VALID = _descriptor.Descriptor(
  name='req_address_valid',
  full_name='nano.api.req_address_valid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='nano.api.req_address_valid.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=60,
)


_RES_ADDRESS_VALID = _descriptor.Descriptor(
  name='res_address_valid',
  full_name='nano.api.res_address_valid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='valid', full_name='nano.api.res_address_valid.valid', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='nano.api.res_address_valid.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['req_address_valid'] = _REQ_ADDRESS_VALID
DESCRIPTOR.message_types_by_name['res_address_valid'] = _RES_ADDRESS_VALID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

req_address_valid = _reflection.GeneratedProtocolMessageType('req_address_valid', (_message.Message,), dict(
  DESCRIPTOR = _REQ_ADDRESS_VALID,
  __module__ = 'util_pb2'
  # @@protoc_insertion_point(class_scope:nano.api.req_address_valid)
  ))
_sym_db.RegisterMessage(req_address_valid)

res_address_valid = _reflection.GeneratedProtocolMessageType('res_address_valid', (_message.Message,), dict(
  DESCRIPTOR = _RES_ADDRESS_VALID,
  __module__ = 'util_pb2'
  # @@protoc_insertion_point(class_scope:nano.api.res_address_valid)
  ))
_sym_db.RegisterMessage(res_address_valid)


# @@protoc_insertion_point(module_scope)
